language: php

php:
  - 5.4

install:

  # Update apt-get
  - sudo apt-get update

  # Install Drush
  - composer self-update
  - composer update
  - composer global require drush/drush:5.9.0
  - which drush
  - drush status
  - phpenv rehash

before_script:

script:

  - echo "hello world"
