language: php

php:
  - 5.4

install:

  # Update apt-get
  - sudo apt-get update
  # Install Drush
  # - pear channel-discover pear.drush.org
  # - pear install drush/drush-5.9.0
  - cd /usr/local
  - phpenv rehash
  - sudo git clone --branch 5.x https://github.com/drush-ops/drush.git drush
  - sudo ln -s /usr/local/drush/drush /usr/bin/drush
  - sudo chmod u+x drush/drush
  - sudo drush --version
  - drush status

before_script:

script:

  - echo "hello world"
