language: php

php:
  - 5.4

install:

  # Update apt-get
  - sudo apt-get update

  # Install Drush
  - cd /usr/local
  - which php
  - export PATH=$PATH:/home/travis/.phpenv/shims/php
  - sudo wget http://pear.drush.org/get/drush-5.9.0.tgz
  - sudo tar -xzvf drush-5.9.0.tgz
  - sudo chmod ugo+x drush-5.9.0/drush
  - sudo ln -s /usr/local/drush-5.9.0/drush /usr/bin/drush
  - sudo ln -s /home/travis/.phpenv/shims/php /usr/bin/php
  - which drush
  - drush status
  - phpenv rehash

  # DEBUG
  - which drush
  - drush status
  - which php
  - php --ini

before_script:

script:

  - echo "hello world"
